### ISSUE TITLE
Add callbacks for control buttons

### ISSUE THREAD

**Issue by lmeninato** [lmeninato/dagsched#9]
- [ ] Add callbacks for each control button (play, pause, etc.)
- [x] Option to display all user DAGs at once.

**Comment by lmeninato** [comment]
@kamzam I got it to display all DAGs at once. Do you want to merge #11 in to your UI changes?

**Comment by lmeninato** [comment]
> @kamzam I got it to display all DAGs at once. Do you want to merge #11 in to your UI changes?

I'll work on the callbacks once you merge your changes in to master. let me know if you need any help with merge conflicts or other git issues.

**Comment by kamzam** [comment]
> @kamzam I got it to display all DAGs at once. Do you want to merge #11 in to your UI changes?

Yes great, saw that in the code. Working on merging that in. :)
